const CATEGORIES=["All","Tutoring","Resume Review","Photo / Video","Coding","Graphic Design","Writing","Other"];
const demoListings=[
{id:"d1",created_at:"2026-08-27T12:00:00Z",title:"Python tutoring for beginners",category:"Coding",description:"1-to-1 help with Python basics, assignments, debugging and exam preparation.",price:"৳500 / hour",student_name:"Nadia Rahman",contact_info:"Telegram: @nadiacodes"},
{id:"d2",created_at:"2026-08-26T15:30:00Z",title:"Professional CV & resume review",category:"Resume Review",description:"I will review your CV, improve wording, formatting and ATS readability.",price:"৳350",student_name:"Arif Hasan",contact_info:"Email: arif.student@example.com"},
{id:"d3",created_at:"2026-08-25T11:15:00Z",title:"Event photography for campus clubs",category:"Photo / Video",description:"Affordable photo coverage for seminars, club events, competitions and portraits.",price:"Trade / ৳1,200",student_name:"Sadia Islam",contact_info:"WhatsApp: +880 1700 000000"},
{id:"d4",created_at:"2026-08-24T09:20:00Z",title:"Calculus & statistics tutoring",category:"Tutoring",description:"Weekly sessions for first-year calculus and introductory statistics.",price:"৳450 / hour",student_name:"Tanvir Ahmed",contact_info:"Telegram: @tanvirlearns"},
{id:"d5",created_at:"2026-08-23T19:00:00Z",title:"Poster & social media design",category:"Graphic Design",description:"Clean posters, event banners, social graphics and presentation covers.",price:"Starts at ৳600",student_name:"Maliha Noor",contact_info:"Email: maliha.design@example.com"},
{id:"d6",created_at:"2026-08-22T13:10:00Z",title:"Frontend website debugging",category:"Coding",description:"Help with HTML, CSS, JavaScript, responsive layouts and fixing UI bugs.",price:"Will trade for English speaking practice",student_name:"Rafi Khan",contact_info:"WhatsApp: +880 1800 000000"}
];
const $=id=>document.getElementById(id);
const cfg=window.CAMPUSX_CONFIG||{};
const connected=!!(cfg.SUPABASE_URL&&cfg.SUPABASE_ANON_KEY);
const sb=connected?supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;
let state={user:null,listings:[],category:"All",query:"",signupMode:false,profile:null,publicProfile:null,publicListing:null,reviews:[],canReview:false,hires:[],threads:[],activeThread:null,messages:[],workspace:"provider",messageChannel:null,notificationChannel:null,notifications:[]};

function safe(v=""){return String(v??"").replace(/[&<>"']/g,s=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[s]))}
function initials(name="User"){return name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase()||"U"}
function openModal(id){$(id)?.classList.remove("hidden");document.body.style.overflow="hidden"}
function closeModal(id){$(id)?.classList.add("hidden");$(id)?.classList.remove("show-threads");document.body.style.overflow=""}
function setAvatar(el,url,name){if(!el)return;el.innerHTML="";if(url){const img=document.createElement("img");img.src=url;img.alt=name||"Student";img.loading="lazy";img.onerror=()=>{el.innerHTML="";el.textContent=initials(name)};el.appendChild(img)}else el.textContent=initials(name)}
function fileToDataURL(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
function profileName(){return state.profile?.full_name||state.user?.user_metadata?.full_name||state.user?.email?.split("@")[0]||"Student"}
function demoKey(prefix){return `campusx-${prefix}-${state.user?.id||"demo-user"}`}
function isUuid(v){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v||"")}
function requireLogin(message="Log in to continue."){if(state.user)return true;setAuthMode(false);$("authMsg").textContent=message;openModal("authModal");return false}

function applyTheme(theme){const value=theme==="dark"?"dark":"light";document.documentElement.dataset.theme=value;localStorage.setItem("campusx-theme",value);if($("themeIcon"))$("themeIcon").textContent=value==="dark"?"☀":"☾";if($("themeLabel"))$("themeLabel").textContent=value==="dark"?"Light":"Dark"}
function initTheme(){const saved=localStorage.getItem("campusx-theme");const preferred=saved||((window.matchMedia&&window.matchMedia("(prefers-color-scheme: dark)").matches)?"dark":"light");applyTheme(preferred)}
function extractEmail(v=""){const m=String(v||"").match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i);return m?m[0].toLowerCase():""}

async function uploadProfileFile(file,folder){if(!sb||!state.user)return null;const ext=(file.name.split(".").pop()||"bin").toLowerCase();const path=`${state.user.id}/${folder}/${Date.now()}.${ext}`;const bucket=sb.storage.from("profile-files");const {error}=await bucket.upload(path,file,{upsert:true,contentType:file.type||undefined,cacheControl:"3600"});if(error){alert(`Photo upload failed: ${error.message}. Run the profile-files storage section in supabase-profile-upgrade.sql.`);return null}const {data}=bucket.getPublicUrl(path);return data?.publicUrl||null}
function demoPublicProfile(item){return{id:item.provider_id||item.student_name,full_name:item.student_name,university:"CampusX student provider",department:item.category,bio:item.description,skills:item.category,mobile:item.contact_info,email:item.contact_info?.includes("@")?item.contact_info.replace(/^.*Email:\s*/i,""):"",portfolio_url:"",avatar_url:"",cv_url:""}}

async function resolveCurrentProvider(){
  if(!sb||!state.publicListing||!isUuid(state.publicListing.id)) return state.publicProfile?.id||state.publicListing?.provider_id||null;
  if(isUuid(state.publicListing.provider_id)) return state.publicListing.provider_id;
  try{
    const {data,error}=await sb.rpc("resolve_legacy_listing_provider",{target_listing:state.publicListing.id});
    if(!error&&isUuid(data)){
      state.publicListing.provider_id=data;
      const local=state.listings.find(x=>String(x.id)===String(state.publicListing.id));
      if(local)local.provider_id=data;
      const {data:profile}=await sb.from("profiles").select("*").eq("id",data).maybeSingle();
      state.publicProfile={...demoPublicProfile(state.publicListing),...(profile||{}),id:data};
      renderPublicProfile();
      return data;
    }
  }catch(_){}
  return null;
}

async function openProvider(item,focusContact=false){state.publicListing=item;if(sb&&!isUuid(item.provider_id)&&isUuid(item.id)){try{const {data:resolved}=await sb.rpc("resolve_legacy_listing_provider",{target_listing:item.id});if(isUuid(resolved))item.provider_id=resolved}catch(_){}}let p=demoPublicProfile(item);if(sb){let data=null;const email=extractEmail(item.contact_info);if(item.provider_id){({data}=await sb.from("profiles").select("*").eq("id",item.provider_id).maybeSingle())}if(!data&&item.student_name){({data}=await sb.from("profiles").select("*").ilike("full_name",item.student_name.trim()).limit(1).maybeSingle())}if(!data&&email){({data}=await sb.from("profiles").select("*").ilike("email",email).limit(1).maybeSingle())}if(!data&&state.user){const mineByEmail=email&&state.user.email?.toLowerCase()===email;const mineByName=item.student_name?.trim().toLowerCase()===profileName().trim().toLowerCase();if(mineByEmail||mineByName)data={...state.profile,id:state.user.id,email:state.user.email||state.profile?.email||""}}if(data)p={...p,...data,id:data.id||item.provider_id||p.id}}else if(state.user&&(item.provider_id===state.user.id||item.student_name===state.profile?.full_name)){p={...p,...state.profile,id:state.user.id,email:state.user.email||state.profile?.email||""}}
state.publicProfile=p;$("feedPage").classList.add("hidden");$("profilePage").classList.add("hidden");$("providerPage").classList.remove("hidden");renderPublicProfile();await loadReviews();await checkReviewPermission();window.scrollTo({top:0,behavior:"smooth"});if(focusContact)setTimeout(()=>$("publicContact")?.scrollIntoView({behavior:"smooth",block:"center"}),180)}
function renderPublicProfile(){const p=state.publicProfile||{},item=state.publicListing||{},nm=p.full_name||item.student_name||"Student";$("publicName").textContent=nm;$("publicUniversity").textContent=[p.university,p.department].filter(Boolean).join(" • ")||"Student provider";$("publicBio").textContent=p.bio||item.description||"Student service provider.";$("publicSkills").textContent=p.skills?`Skills: ${p.skills}`:"";setAvatar($("publicAvatar"),p.avatar_url,nm);const contacts=[];if(p.mobile||p.contact_info)contacts.push(`<div><span class="text-white/35">Mobile / contact</span><div class="mt-1 font-bold">${safe(p.mobile||p.contact_info)}</div></div>`);if(p.email)contacts.push(`<div><span class="text-white/35">Email</span><div class="mt-1"><a class="font-bold text-violet-300" href="mailto:${safe(p.email)}">${safe(p.email)}</a></div></div>`);if(p.portfolio_url)contacts.push(`<div><span class="text-white/35">Portfolio</span><div class="mt-1"><a class="font-bold text-sky-300 hover:underline" target="_blank" rel="noopener" href="${safe(p.portfolio_url)}">Open portfolio ↗</a></div></div>`);$("publicContact").innerHTML=contacts.join("")||'<div class="text-white/40">No public contact details added yet. Use CampusX Messages instead.</div>';$("publicCV").innerHTML=p.cv_url?`<a class="inline-flex rounded-xl bg-sky-400/10 px-4 py-3 font-black text-sky-300" target="_blank" rel="noopener" href="${safe(p.cv_url)}">View CV / Resume ↗</a>`:"No CV uploaded yet.";$("hireName").textContent=nm}

async function loadReviews(){const key=state.publicProfile?.id||state.publicListing?.provider_id||state.publicListing?.student_name;if(sb&&isUuid(state.publicProfile?.id)){const {data}=await sb.from("profile_reviews").select("*").eq("profile_id",state.publicProfile.id).order("created_at",{ascending:false});state.reviews=data||[]}else state.reviews=JSON.parse(localStorage.getItem(`campusx-reviews-${key}`)||"[]");renderReviews()}
function renderReviews(){const rs=state.reviews||[],avg=rs.length?rs.reduce((a,b)=>a+Number(b.rating||0),0)/rs.length:0;$("publicRating").textContent=rs.length?`★ ${avg.toFixed(1)} · ${rs.length} review${rs.length===1?"":"s"}`:"★ New";$("experienceList").innerHTML=rs.length?rs.map(r=>`<div class="rounded-2xl border border-white/10 bg-white/[.04] p-4"><div class="font-black text-amber-200">${"★".repeat(Number(r.rating||0))}<span class="text-white/15">${"★".repeat(5-Number(r.rating||0))}</span></div><p class="mt-2 text-sm leading-6 text-white/55">${safe(r.message)}</p><div class="mt-2 text-xs text-white/25">${safe(r.reviewer_name||"Previous client")}</div></div>`).join(""):'<div class="rounded-2xl border border-dashed border-white/10 p-6 text-sm text-white/35">No client feedback yet.</div>'}
async function checkReviewPermission(){state.canReview=false;if(!state.user){updateReviewUI();return}const pid=state.publicProfile?.id||state.publicListing?.provider_id;if(String(state.user.id)===String(pid)){updateReviewUI("You cannot review your own provider profile.");return}if(sb&&isUuid(pid)){const {data,error}=await sb.from("hire_requests").select("id,status").eq("client_id",state.user.id).eq("provider_id",pid).eq("status","completed").limit(1);if(error)console.warn("Could not check completed hire:",error.message);state.canReview=!!data?.length}else{const hires=JSON.parse(localStorage.getItem(demoKey("hires"))||"[]");state.canReview=hires.some(h=>String(h.provider_key||h.provider_id)===String(pid)&&h.status==="completed")}updateReviewUI()}
function updateReviewUI(custom){const disabled=!state.canReview;$("reviewRating").disabled=disabled;$("reviewMessage").disabled=disabled;$("reviewSubmit").disabled=disabled;$("reviewSubmit").classList.toggle("opacity-40",disabled);$("reviewSubmit").classList.toggle("cursor-not-allowed",disabled);$("reviewHint").textContent=custom||(state.canReview?"Work marked complete — you can now leave feedback.":"Reviews unlock after the provider marks your hired work complete.")}

function renderFilters(){$("filters").innerHTML=CATEGORIES.map(c=>`<button data-cat="${safe(c)}" class="whitespace-nowrap rounded-full border px-4 py-2 text-sm font-black transition ${state.category===c?"border-violet-400/40 bg-violet-500 text-white":"border-white/10 bg-white/5 text-white/55 hover:bg-white/10"}">${safe(c)}</button>`).join("");document.querySelectorAll("[data-cat]").forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;renderFilters();renderListings()})}
function filtered(){const q=state.query.trim().toLowerCase();return state.listings.filter(x=>(state.category==="All"||x.category===state.category)&&(!q||`${x.title} ${x.description} ${x.student_name} ${x.category}`.toLowerCase().includes(q)))}
function renderListings(){const items=filtered();$("count").textContent=`${items.length} active listing${items.length===1?"":"s"}`;$("grid").innerHTML=items.map((x,i)=>`<article class="skill-card cursor-pointer" data-id="${safe(x.id)}" style="animation-delay:${Math.min(i*50,300)}ms"><div class="flex items-start justify-between gap-3"><span class="rounded-full border border-violet-400/20 bg-violet-500/10 px-3 py-1 text-xs font-black text-violet-300">${safe(x.category)}</span><span class="text-xs text-white/25">${x.created_at?new Date(x.created_at).toLocaleDateString(undefined,{month:"short",day:"numeric"}):"New"}</span></div><h3 class="mt-5 text-xl font-black leading-snug">${safe(x.title)}</h3><p class="mt-3 line-clamp-3 text-sm leading-6 text-white/45">${safe(x.description)}</p><div class="mt-6 flex items-end justify-between gap-3 border-t border-white/10 pt-4"><div><div class="font-black">${safe(x.student_name)}</div><div class="mt-1 text-xs text-white/25">Student skill provider</div></div><div class="max-w-[45%] text-right text-sm font-black text-emerald-300">${safe(x.price)}</div></div><button data-id="${safe(x.id)}" class="contact mt-4 w-full rounded-xl border border-white/10 bg-white/5 p-3 text-sm font-black transition hover:bg-white hover:text-slate-950">View profile & contact</button></article>`).join("");document.querySelectorAll(".contact").forEach(b=>b.onclick=e=>{e.stopPropagation();const item=state.listings.find(x=>String(x.id)===b.dataset.id);if(item)openProvider(item,true)});document.querySelectorAll(".skill-card").forEach(card=>card.onclick=()=>{const item=state.listings.find(x=>String(x.id)===card.dataset.id);if(item)openProvider(item)});renderProfileListings()}
async function loadListings(){if(!sb){state.listings=[...demoListings];renderListings();return}const {data,error}=await sb.from("skill_listings").select("*").order("created_at",{ascending:false});state.listings=error?[...demoListings]:(data||[]);renderListings()}

function setAuthMode(signup){state.signupMode=signup;$("name").classList.toggle("hidden",!signup);$("authTitle").textContent=signup?"Create your student account":"Welcome back";$("authSubmit").textContent=signup?"Sign up":"Log in";$("loginTab").className=`flex-1 rounded-xl p-2.5 text-sm font-black ${!signup?"bg-white/10":"text-white/45"}`;$("signupTab").className=`flex-1 rounded-xl p-2.5 text-sm font-black ${signup?"bg-white/10":"text-white/45"}`}
function updateUser(user){state.user=user||null;const yes=!!user;document.body.classList.toggle("auth-required",!yes);$("login").classList.toggle("hidden",yes);$("signup").classList.toggle("hidden",yes);$("profileBtn").classList.toggle("hidden",!yes);$("profileBtn").classList.toggle("flex",yes);$("inboxBtn").classList.toggle("hidden",!yes);$("notificationWrap")?.classList.toggle("hidden",!yes);$("logout").classList.toggle("hidden",!yes);if(yes){closeModal("authModal");const nm=user.user_metadata?.full_name||user.email?.split("@")[0]||"Student";$("profileAvatarMini").textContent=initials(nm);$("studentName").value=nm;$("uniEmail").value=user.email||"";loadHires();loadInboxSummary();subscribeNotifications()}else{setAuthMode(false);openModal("authModal");state.notifications=[];renderNotifications();if(sb&&state.notificationChannel){sb.removeChannel(state.notificationChannel);state.notificationChannel=null}}}
async function loadProfile(){if(!state.user)return;const fallback={id:state.user.id||"demo",full_name:state.user.user_metadata?.full_name||state.user.email?.split("@")[0]||"Student",university:"",department:"",bio:"",skills:"",contact_info:"",mobile:"",portfolio_url:"",avatar_url:"",cv_url:"",email:state.user.email||""};if(!sb){state.profile={...fallback,...JSON.parse(localStorage.getItem("campusx-demo-profile")||"{}")};renderProfile();return}const {data,error}=await sb.from("profiles").select("*").eq("id",state.user.id).maybeSingle();if(error){console.warn("Could not load profile:",error.message);state.profile=fallback}else if(!data){const {data:created,error:createError}=await sb.from("profiles").upsert(fallback,{onConflict:"id"}).select().single();state.profile=createError?fallback:{...fallback,...created}}else state.profile={...fallback,...data,email:data.email||state.user.email||""};renderProfile();await claimLegacyListings()}
async function claimLegacyListings(){if(!sb||!state.user||!state.profile)return;try{await sb.rpc("claim_my_legacy_listings");const {data}=await sb.from("skill_listings").select("*").order("created_at",{ascending:false});if(data){state.listings=data;renderListings()}}catch(_){}}
function renderProfile(){const p=state.profile||{},nm=p.full_name||"Student";$("profileName").textContent=nm;$("profileUniversity").textContent=p.university||"University not added yet";$("profileBio").textContent=p.bio||"Add a short professional bio for clients.";$("profileEmail").textContent=p.email||state.user?.email||"—";$("profileDepartment").textContent=p.department||"—";$("profileMobile").textContent=p.mobile||p.contact_info||"—";$("profilePortfolio").innerHTML=p.portfolio_url?`<a class="text-violet-300 hover:underline" href="${safe(p.portfolio_url)}" target="_blank" rel="noopener">${safe(p.portfolio_url)}</a>`:"—";$("profileCV").innerHTML=p.cv_url?`<a class="text-sky-300 hover:underline" href="${safe(p.cv_url)}" target="_blank" rel="noopener">View / Download CV</a>`:"—";$("profileSkills").textContent=p.skills||"—";setAvatar($("profileAvatar"),p.avatar_url,nm);setAvatar($("profileAvatarMini"),p.avatar_url,nm);$("pfName").value=p.full_name||"";$("pfUniversity").value=p.university||"";$("pfDepartment").value=p.department||"";$("pfMobile").value=p.mobile||p.contact_info||"";$("pfPortfolio").value=p.portfolio_url||"";$("pfSkills").value=p.skills||"";$("pfBio").value=p.bio||"";renderProfileListings()}
function renderProfileListings(){if(!$("profileListings"))return;const email=(state.user?.email||"").toLowerCase(),name=(state.profile?.full_name||"").toLowerCase();let mine=state.listings.filter(x=>x.provider_id&&x.provider_id===state.user?.id);if(!mine.length)mine=state.listings.filter(x=>name&&x.student_name?.toLowerCase()===name);if(!mine.length&&email)mine=state.listings.filter(x=>x.contact_info?.toLowerCase().includes(email));$("profileListings").innerHTML=mine.length?mine.map(x=>`<div class="rounded-2xl border border-white/10 bg-white/[.04] p-4"><div class="flex items-start justify-between gap-3"><div><div class="font-black">${safe(x.title)}</div><div class="mt-1 text-xs text-white/35">${safe(x.category)}</div></div><div class="text-right"><div class="text-sm font-black text-emerald-300">${safe(x.price)}</div><button data-delete-skill="${safe(x.id)}" class="delete-skill-btn mt-3">Delete skill</button></div></div></div>`).join(""):'<div class="rounded-2xl border border-dashed border-white/10 p-8 text-center text-sm text-white/35">No provider listings yet.</div>';document.querySelectorAll("[data-delete-skill]").forEach(b=>b.onclick=()=>deleteSkill(b.dataset.deleteSkill))}
async function deleteSkill(id){if(!state.user)return;if(!confirm("Delete this skill listing? This cannot be undone."))return;const item=state.listings.find(x=>String(x.id)===String(id));if(!item)return;if(sb){if(item.provider_id!==state.user.id){await claimLegacyListings();const refreshed=state.listings.find(x=>String(x.id)===String(id));if(!refreshed||refreshed.provider_id!==state.user.id){alert("CampusX could not verify that this listing belongs to your account.");return}}const {error}=await sb.from("skill_listings").delete().eq("id",id).eq("provider_id",state.user.id);if(error){alert(error.message);return}}state.listings=state.listings.filter(x=>String(x.id)!==String(id));renderListings();renderProfileListings()}
function setWorkspace(mode){state.workspace=mode;const provider=mode==="provider";$("providerWorkspace").classList.toggle("hidden",!provider);$("clientWorkspace").classList.toggle("hidden",provider);$("providerTab").classList.toggle("active",provider);$("clientTab").classList.toggle("active",!provider);$("findMode").classList.toggle("active",!provider);$("offerMode").classList.toggle("active",provider)}
async function showProfile(mode="provider"){if(!requireLogin("Log in to open your CampusX dashboard."))return;$("feedPage").classList.add("hidden");$("providerPage").classList.add("hidden");$("profilePage").classList.remove("hidden");setWorkspace(mode);window.scrollTo({top:0,behavior:"smooth"});await loadProfile();await loadHires();await loadInboxSummary()}
function showFeed(){$("providerPage").classList.add("hidden");$("profilePage").classList.add("hidden");$("feedPage").classList.remove("hidden");$("findMode").classList.add("active");$("offerMode").classList.remove("active");window.scrollTo({top:0,behavior:"smooth"})}
async function saveProfile(e){e.preventDefault();if(!state.user)return;const payload={id:state.user.id,full_name:$("pfName").value.trim(),university:$("pfUniversity").value.trim(),department:$("pfDepartment").value.trim(),contact_info:$("pfMobile").value.trim(),mobile:$("pfMobile").value.trim(),portfolio_url:$("pfPortfolio").value.trim(),skills:$("pfSkills").value.trim(),bio:$("pfBio").value.trim(),email:state.user.email||"",updated_at:new Date().toISOString()};const picture=$("pfPicture").files[0],cv=$("pfCVFile").files[0];if(!sb){if(picture)payload.avatar_url=await fileToDataURL(picture);if(cv)payload.cv_url=await fileToDataURL(cv);localStorage.setItem("campusx-demo-profile",JSON.stringify(payload));state.profile={...state.profile,...payload}}else{if(picture){const up=await uploadProfileFile(picture,"avatars");if(up)payload.avatar_url=up}if(cv){const up=await uploadProfileFile(cv,"cvs");if(up)payload.cv_url=up}const {error}=await sb.from("profiles").upsert(payload,{onConflict:"id"});if(error){alert(error.message);return}await sb.auth.updateUser({data:{full_name:payload.full_name}});state.profile={...state.profile,...payload}}renderProfile();closeModal("editProfileModal")}

function openListing(){if(!requireLogin("Log in before publishing a provider skill."))return;if(state.user){$("studentName").value=state.profile?.full_name||profileName();$("uniEmail").value=state.user.email||"";$("contact").value=state.profile?.mobile||state.profile?.email||state.user.email||""}openModal("listingModal")}

async function openHire(){if(!requireLogin("Log in as a client student to send a hire request."))return;let pid=state.publicProfile?.id;if(sb&&!isUuid(pid))pid=await resolveCurrentProvider();if(state.user.id===pid){alert("You cannot hire your own provider profile.");return}$("hireTitle").value=state.publicListing?.title||"";$("hireDetails").value="";$("hireBudget").value=state.publicListing?.price||"";openModal("hireModal")}
async function submitHire(e){e.preventDefault();if(!requireLogin())return;let pid=state.publicProfile?.id;if(sb&&!isUuid(pid))pid=await resolveCurrentProvider();const linked=isUuid(pid);const row={provider_id:linked?pid:null,client_id:state.user.id,listing_id:isUuid(state.publicListing?.id)?state.publicListing.id:null,listing_title:state.publicListing?.title||$("hireTitle").value.trim(),provider_name:state.publicProfile?.full_name||state.publicListing?.student_name||"Provider",client_name:profileName(),request_title:$("hireTitle").value.trim(),details:$("hireDetails").value.trim(),budget:$("hireBudget").value.trim(),status:linked?"pending":"awaiting_provider_link",created_at:new Date().toISOString()};if(sb){const {error}=await sb.from("hire_requests").insert(row);if(error){alert(error.message);return}}else{const arr=JSON.parse(localStorage.getItem(demoKey("hires"))||"[]");arr.unshift({...row,id:crypto.randomUUID(),provider_key:pid});localStorage.setItem(demoKey("hires"),JSON.stringify(arr))}closeModal("hireModal");if(linked){alert("Hire request sent. You can message the provider from CampusX Messages.");await startConversation(true)}else{alert("Hire request saved. This legacy listing is not linked to a CampusX account yet; the request will attach automatically when the provider signs in and claims the listing. You can use the contact details on this profile in the meantime.")}await loadHires();await checkReviewPermission()}
async function loadHires(){if(!state.user)return;if(sb){const {data,error}=await sb.from("hire_requests").select("*").or(`client_id.eq.${state.user.id},provider_id.eq.${state.user.id}`).order("created_at",{ascending:false});if(error)console.warn("Could not load hire requests:",error.message);state.hires=data||[]}else state.hires=JSON.parse(localStorage.getItem(demoKey("hires"))||"[]");renderHires();renderHireInbox();await loadNotifications()}
function statusBadge(s){const map={pending:"text-amber-300 bg-amber-400/10",accepted:"text-sky-300 bg-sky-400/10",completed:"text-emerald-300 bg-emerald-400/10",declined:"text-rose-300 bg-rose-400/10",awaiting_provider_link:"text-violet-300 bg-violet-400/10"};return `<span class="rounded-full px-2.5 py-1 text-[10px] font-black uppercase ${map[s]||"text-white/50 bg-white/5"}">${safe(s)}</span>`}
function renderHires(){const incoming=state.hires.filter(h=>String(h.provider_id)===String(state.user?.id)),outgoing=state.hires.filter(h=>String(h.client_id)===String(state.user?.id)||(!sb&&h.client_name===profileName()));$("providerHires").innerHTML=incoming.length?incoming.map(h=>`<div class="hire-card"><div class="hire-row"><div><b>${safe(h.client_name||"Client student")}</b><div class="muted">${safe(h.request_title||h.listing_title||"Hire request")}</div></div>${statusBadge(h.status)}</div><p>${safe(h.details||"")}</p>${h.status==="pending"?`<div class="hire-actions"><button data-hire-action="accepted" data-hire-id="${safe(h.id)}" class="button small secondary">Accept</button><button data-hire-action="declined" data-hire-id="${safe(h.id)}" class="button small ghost">Decline</button></div>`:h.status==="accepted"?`<button data-hire-action="completed" data-hire-id="${safe(h.id)}" class="button small primary">Mark work complete</button>`:""}</div>`).join(""):'<div class="empty-state">No client hire requests yet.</div>';$("clientHires").innerHTML=outgoing.length?outgoing.map(h=>`<div class="hire-card"><div class="hire-row"><div><b>${safe(h.provider_name||"Provider student")}</b><div class="muted">${safe(h.request_title||h.listing_title||"Hire request")}</div></div>${statusBadge(h.status)}</div>${h.status==="completed"?`<button data-review-hire-id="${safe(h.id)}" class="button small secondary">Leave feedback</button>`:""}</div>`).join(""):'<div class="empty-state">You have not hired a student yet.</div>';document.querySelectorAll("[data-hire-action]").forEach(b=>b.onclick=()=>updateHireStatus(b.dataset.hireId,b.dataset.hireAction));document.querySelectorAll("[data-review-hire-id]").forEach(b=>b.onclick=()=>openReviewForHire(state.hires.find(h=>String(h.id)===String(b.dataset.reviewHireId))))}
async function updateHireStatus(id,status){if(sb){const {error}=await sb.from("hire_requests").update({status,updated_at:new Date().toISOString()}).eq("id",id).eq("provider_id",state.user.id);if(error){alert(error.message);return}}else{const arr=JSON.parse(localStorage.getItem(demoKey("hires"))||"[]");const h=arr.find(x=>String(x.id)===String(id));if(h)h.status=status;localStorage.setItem(demoKey("hires"),JSON.stringify(arr))}await loadHires()}

async function getOrCreateConversation(){if(!state.user)return null;let pid=state.publicProfile?.id;if(sb&&!isUuid(pid))pid=await resolveCurrentProvider();if(state.user.id===pid)return null;if(sb){if(!isUuid(pid)){alert("Direct CampusX messaging will activate as soon as this legacy listing is linked to its provider account. You can still send a hire request now, and use the provider contact details shown on the profile.");return null}const {data:found}=await sb.from("conversations").select("*").eq("provider_id",pid).eq("client_id",state.user.id).limit(1).maybeSingle();if(found)return found;const payload={provider_id:pid,client_id:state.user.id,listing_id:isUuid(state.publicListing?.id)?state.publicListing.id:null,provider_name:state.publicProfile?.full_name||state.publicListing?.student_name||"Provider",client_name:profileName(),listing_title:state.publicListing?.title||"CampusX conversation"};const {data,error}=await sb.from("conversations").insert(payload).select().single();if(error){alert(error.message);return null}return data}else{const key=demoKey("threads"),arr=JSON.parse(localStorage.getItem(key)||"[]");let t=arr.find(x=>x.provider_key===pid);if(!t){t={id:crypto.randomUUID(),provider_key:pid,provider_id:pid,client_id:state.user.id,provider_name:state.publicProfile?.full_name||"Provider",client_name:profileName(),listing_title:state.publicListing?.title||"CampusX conversation",created_at:new Date().toISOString()};arr.unshift(t);localStorage.setItem(key,JSON.stringify(arr))}return t}}
async function startConversation(silent=false){if(!requireLogin("Log in to message this student."))return;const t=await getOrCreateConversation();if(!t)return;state.activeThread=t;if(!silent){openModal("chatModal");await loadThreads();await openThread(t.id)}}
async function loadInboxSummary(){if(!state.user)return;if(sb){const {data}=await sb.from("conversations").select("*").or(`client_id.eq.${state.user.id},provider_id.eq.${state.user.id}`).order("updated_at",{ascending:false});state.threads=data||[]}else state.threads=JSON.parse(localStorage.getItem(demoKey("threads"))||"[]");$("inboxCount").textContent=state.threads.length;renderThreadPreviews();await loadNotifications()}
function renderThreadPreviews(){const top=state.threads.slice(0,4),html=top.length?top.map(t=>`<button data-thread-preview="${safe(t.id)}" class="rounded-xl border border-white/10 bg-white/[.04] p-3 text-left"><div class="font-black">${safe(otherName(t))}</div><div class="mt-1 truncate text-xs text-white/35">${safe(t.listing_title||"CampusX message")}</div></button>`).join(""):'<div class="rounded-xl border border-dashed border-white/10 p-5 text-sm text-white/35">No conversations yet.</div>';$("clientThreads").innerHTML=html;document.querySelectorAll("[data-thread-preview]").forEach(b=>b.onclick=()=>{openInbox().then(()=>openThread(b.dataset.threadPreview))})}
function otherName(t){return t.provider_id===state.user?.id?(t.client_name||"Client student"):(t.provider_name||"Provider student")}
function notificationSender(m){const t=state.threads.find(x=>String(x.id)===String(m.conversation_id));return t?otherName(t):(m.sender_name||m.client_name||m.provider_name||"CampusX student")}
function hireNotificationKey(h){return `campusx-hire-read-${state.user?.id||"guest"}-${h.id}`}
function isHireNotificationRead(h){return localStorage.getItem(hireNotificationKey(h))==="1"}
function markHireNotificationRead(h){if(h&&h.id)localStorage.setItem(hireNotificationKey(h),"1")}
async function loadNotifications(){if(!state.user)return;const notifications=[];if(sb){const threadIds=state.threads.map(t=>t.id).filter(Boolean);if(threadIds.length){const {data,error}=await sb.from("messages").select("id,conversation_id,sender_id,sender_name,body,message,created_at,read_at").in("conversation_id",threadIds).neq("sender_id",state.user.id).is("read_at",null).order("created_at",{ascending:false}).limit(20);if(!error)(data||[]).forEach(m=>notifications.push({...m,kind:"message"}))}}else{for(const t of state.threads){const arr=JSON.parse(localStorage.getItem(`campusx-messages-${t.id}`)||"[]");arr.filter(m=>m.sender_id!==state.user.id&&!m.read_at).forEach(m=>notifications.push({...m,kind:"message"}))}}(state.hires||[]).filter(h=>((String(h.provider_id)===String(state.user.id)&&["pending","accepted"].includes(h.status))||(String(h.client_id)===String(state.user.id)&&h.status==="completed"))&&!isHireNotificationRead(h)).forEach(h=>notifications.push({...h,kind:"hire"}));state.notifications=notifications.sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).slice(0,20);renderNotifications()}
function renderNotifications(){const list=$("notificationList"),count=$("notificationCount");if(!list||!count)return;const n=state.notifications.length;count.textContent=n>99?"99+":String(n);count.classList.toggle("hidden",!n);list.innerHTML=n?state.notifications.map(m=>m.kind==="hire"?`<button class="notification-item" data-notif-hire="${safe(m.id)}"><div class="flex items-center justify-between gap-3"><span class="notif-name">Hiring update</span><span class="h-2 w-2 shrink-0 rounded-full bg-emerald-400"></span></div><div class="notif-text">${safe(m.provider_id===state.user?.id?`${m.client_name||"A client"} sent a hire request`:`Your work is ${m.status}`)}</div><div class="notif-time">${safe(m.created_at?new Date(m.created_at).toLocaleString():"")}</div></button>`:`<button class="notification-item" data-notif-thread="${safe(m.conversation_id)}"><div class="flex items-center justify-between gap-3"><span class="notif-name">${safe(notificationSender(m))}</span><span class="h-2 w-2 shrink-0 rounded-full bg-violet-400"></span></div><div class="notif-text">${safe(m.body||m.message||"New message")}</div><div class="notif-time">${safe(m.created_at?new Date(m.created_at).toLocaleString():"")}</div></button>`).join(""):'<div class="px-3 py-8 text-center text-xs text-white/35">You are all caught up.</div>';document.querySelectorAll("[data-notif-thread]").forEach(b=>b.onclick=async()=>{toggleNotificationMenu(false);await openInbox();await openThread(b.dataset.notifThread)});document.querySelectorAll("[data-notif-hire]").forEach(b=>b.onclick=async()=>{const h=state.notifications.find(x=>x.kind==="hire"&&String(x.id)===String(b.dataset.notifHire));markHireNotificationRead(h);state.notifications=state.notifications.filter(x=>x!==h);renderNotifications();toggleNotificationMenu(false);await openInbox();setInboxTab("hiring")})}
function toggleNotificationMenu(force){const menu=$("notificationMenu"),btn=$("notificationBtn");if(!menu)return;const open=force===undefined?menu.classList.contains("hidden"):!!force;menu.classList.toggle("hidden",!open);btn?.setAttribute("aria-expanded",String(open))}
async function markThreadRead(id){if(!state.user)return false;if(sb){const {error}=await sb.rpc("mark_conversation_messages_read",{target_conversation:id});if(error){console.warn("Could not mark conversation read:",error.message);return false}}else{const key=`campusx-messages-${id}`,arr=JSON.parse(localStorage.getItem(key)||"[]");arr.forEach(m=>{if(m.sender_id!==state.user.id)m.read_at=new Date().toISOString()});localStorage.setItem(key,JSON.stringify(arr))}state.notifications=state.notifications.filter(m=>String(m.conversation_id)!==String(id));renderNotifications();return true}
async function markAllNotificationsRead(){if(!state.user)return;if(sb){const {error}=await sb.rpc("mark_all_my_messages_read");if(error){console.warn("Could not mark all notifications read:",error.message);const ids=[...new Set(state.notifications.filter(m=>m.kind==="message").map(m=>m.conversation_id))];for(const id of ids)await markThreadRead(id)}}else{const ids=[...new Set(state.notifications.filter(m=>m.kind==="message").map(m=>m.conversation_id))];for(const id of ids)await markThreadRead(id)}state.notifications.filter(m=>m.kind==="hire").forEach(markHireNotificationRead);await loadNotifications()}
function subscribeNotifications(){if(!sb||!state.user)return;if(state.notificationChannel)sb.removeChannel(state.notificationChannel);state.notificationChannel=sb.channel(`campusx-notifications-${state.user.id}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"messages"},payload=>{if(payload.new.sender_id!==state.user.id){loadInboxSummary()}}).on("postgres_changes",{event:"DELETE",schema:"public",table:"messages"},()=>loadNotifications()).on("postgres_changes",{event:"INSERT",schema:"public",table:"hire_requests"},payload=>{if(String(payload.new.provider_id)===String(state.user.id)||String(payload.new.client_id)===String(state.user.id)){loadHires();loadInboxSummary()}}).on("postgres_changes",{event:"UPDATE",schema:"public",table:"hire_requests"},payload=>{if(String(payload.new.provider_id)===String(state.user.id)||String(payload.new.client_id)===String(state.user.id)){loadHires();loadInboxSummary()}}).subscribe()}
function renderHireInbox(){const box=$("hireInbox");if(!box)return;const relevant=state.hires.filter(h=>String(h.provider_id)===String(state.user?.id)||String(h.client_id)===String(state.user?.id));box.innerHTML=relevant.length?`${relevant.slice(0,5).map(h=>{const incoming=String(h.provider_id)===String(state.user.id);return `<div class="hire-inbox-card"><div class="hire-inbox-top"><b>${safe(incoming?h.client_name||"Client student":h.provider_name||"Provider student")}</b>${statusBadge(h.status)}</div><div class="hire-inbox-title">${safe(h.request_title||h.listing_title||"Hire request")}</div><div class="hire-inbox-details">${safe(h.details||"No project details added.")}</div><div class="hire-inbox-details">${safe(h.budget||"Budget not specified")}</div>${incoming&&h.status==="pending"?`<div class="hire-inbox-actions"><button data-hire-action="accepted" data-hire-id="${safe(h.id)}" class="button small secondary">Accept</button><button data-hire-action="declined" data-hire-id="${safe(h.id)}" class="button small ghost">Decline</button></div>`:incoming&&h.status==="accepted"?`<button data-hire-action="completed" data-hire-id="${safe(h.id)}" class="button small primary">Mark complete</button>`:h.status==="completed"&&!incoming?`<button data-review-hire-id="${safe(h.id)}" class="button small secondary">Leave feedback</button>`:""}</div>`}).join("")}`:"<div class=\"empty-state\">No hiring details yet.</div>";box.querySelectorAll("[data-hire-action]").forEach(b=>b.onclick=()=>updateHireStatus(b.dataset.hireId,b.dataset.hireAction));box.querySelectorAll("[data-review-hire-id]").forEach(b=>b.onclick=()=>openReviewForHire(state.hires.find(h=>String(h.id)===String(b.dataset.reviewHireId))))}
function openReviewForHire(h){if(!h||h.status!=="completed")return;closeModal("chatModal");state.reviewHire=h;$("reviewProviderName").textContent=h.provider_name||"this provider";$("reviewWorkTitle").textContent=h.request_title||h.listing_title||"Completed work";$("directReviewMessage").value="";openModal("reviewModal")}
async function openProviderForHire(h){if(!h)return;let listing=state.listings.find(x=>String(x.id)===String(h.listing_id));if(!listing)listing={id:h.listing_id||h.provider_id,title:h.listing_title||h.request_title,student_name:h.provider_name||"Provider student",provider_id:h.provider_id,description:h.details||"",price:h.budget||""};await openProvider(listing,false)}
async function loadThreads(){await loadInboxSummary();const previews={};if(sb&&state.threads.length){const {data}=await sb.from("messages").select("conversation_id,body,created_at,sender_id").in("conversation_id",state.threads.map(t=>t.id)).order("created_at",{ascending:false});const active=new Set((data||[]).map(m=>String(m.conversation_id)));(data||[]).forEach(m=>{if(!previews[m.conversation_id])previews[m.conversation_id]=m});state.threads=state.threads.filter(t=>active.has(String(t.id)))}else if(!sb){state.threads=state.threads.filter(t=>{const messages=JSON.parse(localStorage.getItem(`campusx-messages-${t.id}`)||"[]");if(messages.length)previews[t.id]=messages[messages.length-1];return messages.length})}await loadHires();renderHireInbox();$("threadList").innerHTML=state.threads.length?state.threads.map(t=>{const name=otherName(t),last=previews[t.id],preview=last?.body||"Start a conversation";return `<button data-thread-id="${safe(t.id)}" class="thread-item ${state.activeThread?.id===t.id?"active":""}"><span class="thread-avatar">${safe(initials(name))}<i></i></span><span class="thread-copy"><span class="thread-topline"><b>${safe(name)}</b><time>${safe(last?.created_at?new Date(last.created_at).toLocaleDateString(undefined,{month:"short",day:"numeric"}):"")}</time></span><span class="thread-preview">${safe(preview)}</span><span class="thread-context">${safe(t.listing_title||"CampusX conversation")}</span></span></button>`}).join(""):'<div class="thread-empty"><span class="thread-empty-icon">✉</span><b>No messages yet</b><span>Start a conversation from a student profile.</span></div>';document.querySelectorAll("[data-thread-id]").forEach(b=>b.onclick=()=>openThread(b.dataset.threadId))}
async function openInbox(){if(!requireLogin("Log in to open messages."))return;toggleNotificationMenu(false);openModal("chatModal");const mobile=window.matchMedia("(max-width: 699px)").matches;if(mobile){setInboxTab("messages");$("chatModal").classList.add("show-threads")}await loadThreads();if(!mobile&&(state.activeThread||state.threads[0]))await openThread((state.activeThread||state.threads[0]).id)}
async function openThread(id){const t=state.threads.find(x=>String(x.id)===String(id))||state.activeThread;if(!t)return;state.activeThread=t;$("chatHeader").textContent=`${otherName(t)} • ${t.listing_title||"CampusX"}`;$("chatModal").classList.remove("show-threads");$("messageForm").classList.remove("hidden");if(sb){const {data}=await sb.from("messages").select("*").eq("conversation_id",t.id).order("created_at",{ascending:true});state.messages=data||[]}else state.messages=JSON.parse(localStorage.getItem(`campusx-messages-${t.id}`)||"[]");renderMessages();await markThreadRead(t.id);await loadThreads();subscribeMessages(t.id)}
function renderMessages(){$("messageList").innerHTML=state.messages.length?state.messages.map(m=>`<div class="message-bubble ${m.sender_id===state.user?.id?"mine":""}">${m.sender_id===state.user?.id?`<div class="message-actions"><button class="delete-message-btn" data-delete-message="${safe(m.id)}" title="Delete message">Delete</button></div>`:""}<div class="pr-12">${safe(m.body||m.message||"")}</div><div class="message-sender">${safe(m.sender_name||notificationSender(m)||"Student")}</div></div>`).join(""):'<div class="grid h-full place-items-center text-sm text-white/30">Start the conversation.</div>';document.querySelectorAll("[data-delete-message]").forEach(b=>b.onclick=()=>deleteMessage(b.dataset.deleteMessage));$("messageList").scrollTop=$("messageList").scrollHeight}
async function deleteMessage(id){const m=state.messages.find(x=>String(x.id)===String(id));if(!m||String(m.sender_id)!==String(state.user?.id))return;if(!confirm("Delete this message permanently for both students?"))return;if(sb){let deleted=false;try{const {data,error}=await sb.rpc("delete_own_message",{target_message:String(id)});if(error)throw error;deleted=!!data}catch(err){alert(`Could not delete message: ${err.message||err}`);return}if(!deleted){alert("The message was not deleted. Run the latest CampusX SQL fix in Supabase, then try again.");await openThread(state.activeThread.id);return}const {data:check,error:checkError}=await sb.from("messages").select("id").eq("id",id).maybeSingle();if(checkError){alert(checkError.message);return}if(check){alert("Supabase still has this message, so it was not removed. Please run final-message-delete-fix.sql.");return}}else{const key=`campusx-messages-${state.activeThread.id}`;state.messages=state.messages.filter(x=>String(x.id)!==String(id));localStorage.setItem(key,JSON.stringify(state.messages))}state.messages=state.messages.filter(x=>String(x.id)!==String(id));renderMessages();await loadNotifications()}
function subscribeMessages(conversationId){if(!sb)return;if(state.messageChannel)sb.removeChannel(state.messageChannel);state.messageChannel=sb.channel(`messages-${conversationId}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"messages",filter:`conversation_id=eq.${conversationId}`},payload=>{if(!state.messages.some(m=>m.id===payload.new.id)){state.messages.push(payload.new);renderMessages();if(payload.new.sender_id!==state.user?.id)markThreadRead(conversationId)}}).on("postgres_changes",{event:"DELETE",schema:"public",table:"messages",filter:`conversation_id=eq.${conversationId}`},payload=>{state.messages=state.messages.filter(m=>String(m.id)!==String(payload.old.id));renderMessages()}).subscribe()}
async function sendMessage(e){e.preventDefault();const body=$("messageInput").value.trim();if(!body||!state.activeThread)return;const row={conversation_id:state.activeThread.id,sender_id:state.user.id,sender_name:profileName(),body,message:body,created_at:new Date().toISOString()};if(sb){const {data,error}=await sb.from("messages").insert(row).select().single();if(error){alert(error.message);return}if(!state.messages.some(m=>m.id===data.id))state.messages.push(data);await sb.from("conversations").update({updated_at:new Date().toISOString()}).eq("id",state.activeThread.id)}else{row.id=crypto.randomUUID();state.messages.push(row);localStorage.setItem(`campusx-messages-${state.activeThread.id}`,JSON.stringify(state.messages))}$("messageInput").value="";renderMessages()}

initTheme();showFeed();setInboxTab("messages");$("category").innerHTML=CATEGORIES.slice(1).map(c=>`<option>${safe(c)}</option>`).join("");renderFilters();loadListings();if($("themeToggle"))$("themeToggle").onclick=()=>applyTheme(document.documentElement.dataset.theme==="dark"?"light":"dark");if($("authThemeToggle"))$("authThemeToggle").onclick=()=>applyTheme(document.documentElement.dataset.theme==="dark"?"light":"dark");
$("login").onclick=()=>{setAuthMode(false);$("authMsg").textContent="";openModal("authModal")};$("signup").onclick=()=>{setAuthMode(true);$("authMsg").textContent="";openModal("authModal")};$("loginTab").onclick=()=>setAuthMode(false);$("signupTab").onclick=()=>setAuthMode(true);
$("authForm").onsubmit=async e=>{e.preventDefault();$("authMsg").textContent="";if(!sb){const fake={id:"demo-user",email:$("email").value,user_metadata:{full_name:$("name").value||"Demo Student"}};updateUser(fake);closeModal("authModal");await loadProfile();return}const result=state.signupMode?await sb.auth.signUp({email:$("email").value,password:$("password").value,options:{data:{full_name:$("name").value.trim()},emailRedirectTo:"https://wolfbackcse.github.io/CampusX.web/"}}):await sb.auth.signInWithPassword({email:$("email").value,password:$("password").value});if(result.error){$("authMsg").textContent=result.error.message;return}if(state.signupMode&&!result.data.session){$("authMsg").textContent="Account created. Check your email and confirm it, then log in.";return}updateUser(result.data.user);closeModal("authModal");await loadProfile()};
$("logout").onclick=async()=>{if(sb)await sb.auth.signOut();updateUser(null);showFeed()};
["post","postTop","profilePostBtn"].forEach(id=>$(id).onclick=openListing);
$("listingForm").onsubmit=async e=>{e.preventDefault();if(!requireLogin())return;const payload={title:$("title").value.trim(),category:$("category").value,description:$("description").value.trim(),price:$("price").value.trim(),student_name:$("studentName").value.trim(),contact_info:$("contact").value.trim(),provider_id:state.user.id};if(sb&&state.user.email?.toLowerCase()!==$("uniEmail").value.trim().toLowerCase()){alert("University email must match your logged-in account.");return}if(sb){const {data,error}=await sb.from("skill_listings").insert(payload).select().single();if(error){alert(error.message);return}state.listings.unshift(data)}else state.listings.unshift({...payload,id:crypto.randomUUID(),created_at:new Date().toISOString()});e.target.reset();closeModal("listingModal");renderListings();showProfile("provider")};
function doSearch(v){state.query=v.toLowerCase();if($("search"))$("search").value=v;if($("searchMobile"))$("searchMobile").value=v;renderListings()}$("search").oninput=e=>doSearch(e.target.value);$("searchMobile").oninput=e=>doSearch(e.target.value);$("browseBtn").onclick=()=>$("marketplace").scrollIntoView({behavior:"smooth"});$("profileBtn").onclick=()=>showProfile("provider");$("homeBtn").onclick=$("backToFeed").onclick=$("backFromProvider").onclick=showFeed;$("offerMode").onclick=()=>showProfile("provider");$("findMode").onclick=showFeed;$("providerTab").onclick=()=>setWorkspace("provider");$("clientTab").onclick=()=>setWorkspace("client");$("editProfileBtn").onclick=()=>openModal("editProfileModal");$("profileForm").onsubmit=saveProfile;
$("hireProviderBtn").onclick=openHire;$("messageProviderBtn").onclick=()=>startConversation(false);$("hireForm").onsubmit=submitHire;$("messageForm").onsubmit=sendMessage;$("inboxBtn").onclick=openInbox;document.querySelectorAll("[data-open-inbox]").forEach(b=>b.onclick=openInbox);if($("notificationBtn"))$("notificationBtn").onclick=e=>{e.stopPropagation();toggleNotificationMenu()};if($("notificationOpenInbox"))$("notificationOpenInbox").onclick=openInbox;if($("markAllReadBtn"))$("markAllReadBtn").onclick=markAllNotificationsRead;document.addEventListener("click",e=>{if(!$("notificationWrap")?.contains(e.target))toggleNotificationMenu(false)});
$("mobileMenuBtn").onclick=e=>{e.stopPropagation();const menu=$("mobileMenu"),open=menu.classList.contains("hidden");menu.classList.toggle("hidden",!open);$("mobileMenuBtn").setAttribute("aria-expanded",String(open))};$("mobileMenuHome").onclick=()=>{closeMobileMenu();showFeed()};$("mobileMenuMessages").onclick=()=>{closeMobileMenu();openInbox()};$("mobileMenuProfile").onclick=()=>{closeMobileMenu();showProfile("provider")};$("mobileMenuLogout").onclick=()=>{closeMobileMenu();$("logout").click()};document.addEventListener("click",e=>{if(!$("mobileMenu")?.contains(e.target)&&e.target!==$("mobileMenuBtn"))closeMobileMenu()});function closeMobileMenu(){const menu=$("mobileMenu");if(menu){menu.classList.add("hidden");$("mobileMenuBtn")?.setAttribute("aria-expanded","false")}}
function setInboxTab(tab){const messages=tab==="messages";$("messagesTab")?.classList.toggle("active",messages);$("hiringTab")?.classList.toggle("active",!messages);$("messageInboxPanel")?.classList.toggle("hidden",!messages);$("hiringInboxPanel")?.classList.toggle("hidden",messages)}
$("messagesTab").onclick=()=>setInboxTab("messages");$("hiringTab").onclick=()=>setInboxTab("hiring");$("chatThreadsBtn").onclick=()=>{setInboxTab("messages");$("chatModal").classList.add("show-threads")};$("chatProfileBtn").onclick=()=>{if(state.activeThread?.provider_id&&String(state.activeThread.provider_id)!==String(state.user?.id)){const item=state.listings.find(x=>String(x.provider_id)===String(state.activeThread.provider_id));if(item)openProvider(item)}};
$("reviewForm").onsubmit=async e=>{e.preventDefault();if(!state.canReview){alert("Review unlocks after the provider marks the hired work complete.");return}const rating=Number($("reviewRating").value),message=$("reviewMessage").value.trim(),p=state.publicProfile||{},row={rating,message,reviewer_name:profileName(),created_at:new Date().toISOString()};if(sb&&isUuid(p.id)){const {error}=await sb.from("profile_reviews").insert({profile_id:p.id,reviewer_id:state.user.id,reviewer_name:profileName(),rating,message});if(error){alert(error.message);return}}else{const key=p.id||state.publicListing?.student_name,arr=JSON.parse(localStorage.getItem(`campusx-reviews-${key}`)||"[]");arr.unshift(row);localStorage.setItem(`campusx-reviews-${key}`,JSON.stringify(arr))}$("reviewMessage").value="";state.canReview=false;await loadReviews();updateReviewUI("Thanks — your review was added.")};
$("directReviewForm").onsubmit=async e=>{e.preventDefault();const h=state.reviewHire;if(!h||h.status!=="completed")return;const rating=Number($("directReviewRating").value),message=$("directReviewMessage").value.trim();if(!message)return;const row={rating,message,reviewer_name:profileName(),created_at:new Date().toISOString()};if(sb&&isUuid(h.provider_id)){const {error}=await sb.from("profile_reviews").insert({profile_id:h.provider_id,reviewer_id:state.user.id,reviewer_name:profileName(),rating,message});if(error){alert(`Could not submit feedback: ${error.message}`);return}}else{const key=h.provider_id||h.provider_name,arr=JSON.parse(localStorage.getItem(`campusx-reviews-${key}`)||"[]");arr.unshift(row);localStorage.setItem(`campusx-reviews-${key}`,JSON.stringify(arr))}closeModal("reviewModal");await loadHires();alert("Thanks — your feedback was added.")};
document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>{closeModal("authModal");closeModal("listingModal")});document.querySelectorAll("[data-close-profile]").forEach(b=>b.onclick=()=>closeModal("editProfileModal"));document.querySelectorAll("[data-close-hire]").forEach(b=>b.onclick=()=>closeModal("hireModal"));document.querySelectorAll("[data-close-review]").forEach(b=>b.onclick=()=>closeModal("reviewModal"));document.querySelectorAll("[data-close-chat]").forEach(b=>b.onclick=()=>closeModal("chatModal"));document.querySelectorAll("[data-page-close]").forEach(b=>b.onclick=showFeed);document.querySelectorAll(".modal-backdrop").forEach(b=>b.onclick=()=>{["authModal","listingModal","editProfileModal","hireModal","reviewModal","chatModal"].forEach(closeModal)});
if(sb){sb.auth.getSession().then(async({data})=>{updateUser(data.session?.user||null);if(data.session?.user)await loadProfile()});sb.auth.onAuthStateChange(async(_,session)=>{updateUser(session?.user||null);if(session?.user)await loadProfile()})}
